#
# Run OVMS server
# set the configuration in ./conf/
#
# The container will initialize the DB (DEMO car and user DEMO)
#
FROM alpine:latest
RUN apk update
RUN apk add git sed bash perl netcat-openbsd mysql-client make tzdata
# needed for PW hashing
RUN apk add apache2-utils
# Required perl modules
RUN apk add perl-dbi perl-dbd-mysql perl-anyevent-http perl-digest-hmac perl-config-inifiles perl-uri perl-json-xs 
RUN apk add perl-crypt-rc4 perl-ev perl-data-uuid perl-protocol-websocket perl-anyevent perl-app-cpanminus

RUN cpanm AnyEvent::HTTPD

RUN mkdir -p /usr/src/app
RUN git clone --depth 1 https://github.com/openvehicles/Open-Vehicle-Server.git /usr/src/app/ovms
RUN cp -r /usr/src/app/ovms/v3/server  /usr/src/app/server
RUN rm -rf /usr/src/app/ovms

# CRYPT::RC4::XS not available and cpanm fails -> utilize Crypt::RC4 instead
RUN find /usr/src/app -regex '.*\.\(pl\|pm\)' -exec sed -i -e 's/RC4::XS/RC4/g' {} \;

# fix bug in DbDBI.pm - table ovms_owners property deleted of owner checked as datetime. Should be a tinyint(1)
RUN  find /usr/src/app/ -name "DbDBI.pm" -exec sed -i -e 's/deleted="0000-00-00 00:00:00"/deleted=0/g' {} \; 

COPY ./scripts/ctrl-DB.sh  /usr/src/app
RUN chmod +x /usr/src/app/ctrl-DB.sh
COPY ./scripts/check-and-run.sh  /usr/src/app
RUN chmod +x /usr/src/app/check-and-run.sh
WORKDIR /usr/src/app
ENTRYPOINT [ "/usr/src/app/check-and-run.sh" ]
